/**
 * LeetCode 38 - Count and Say
 * Description:
 * The count-and-say sequence is generated by describing the previous term.
 * Example:
 * 1 -> "1"
 * 2 -> "11"      (one 1)
 * 3 -> "21"      (two 1s)
 * 4 -> "1211"    (one 2, one 1)
 * 5 -> "111221"  (one 1, one 2, two 1s)
* Time Complexity: O(T) where T is the total number of characters processed
 * Space Complexity: O(L) where L is the length of the final generated string.
 */
package strings;

public class CountNSay {

    public static String countAndSay(int n) {

        if (n == 1) {
            return "1";
        }

        String current = "1";

        for (int step = 0; step < n - 1; step++) {

            StringBuilder next = new StringBuilder();

            int i = 0;

            while (i < current.length()) {

                char digit = current.charAt(i);
                int count = 1;
                i++;

                while (i < current.length() && current.charAt(i) == digit) {
                    count++;
                    i++;
                }
                next.append(count);
                next.append(digit);
            }

            current = next.toString();
        }

        return current;
    }

    public static void main(String[] args) {

        int[] testCases = {1, 2, 3, 4, 5, 6};

        for (int n : testCases) {
            System.out.println("n = " + n + countAndSay(n));
        }
    }
}

